version: "3"
services:
  app:
    container_name: "fastapi_app"
    restart: always
    build: . # Current directory!
    command: "/usr/local/bin/gunicorn --preload -b 0.0.0.0:8000 -w 4 -k uvicorn.workers.UvicornWorker app.main:app"
    volumes:
      - "./:/fastapi"
      - "./app/static:/fastapi/app/static"
    environment:
      PYTHON UNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
      APP_NAME: "fast api"
      ADMIN_EMAIL: "gracysusant@gmail.com"
      DB_URL: "mysql+mysqlconnector://root:root@mysql:3306/fastapi"
      SCRAP_API_TOKEN: "dd424a4ae2c60473bb07132def3b89a1"
    ports:
      - "8000:8000"
    depends_on:
      - mysql
  mysql:
    container_name: "fastapi_mysql"
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - "~/.fastapi/data/mysql:/var/lib/mysql"
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fastapi
      - MYSQL_PASSWORD=root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "fastapi_pma"
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - "8200:80"